### PR TITLE
Upgrade to v4.11.0

### PR DESCRIPTION
**Pull request by yogeshk25**
This PR upgrade dfu library to v4.11.0.
This solves crash fix when dfu upload is in progress and user turns off bluetooth.
And many other fixes

### CODE REVIEW

**Comment by yogeshk25** [comment]
@framinosona  Can you release new version on nuget store?

**Comment by framinosona** [comment]
Hi @yogeshk25, I see you've removed the simulator part, any reason? Was it the cause of issues?

**Comment by yogeshk25** [comment]
Yes, lipo command was failing.

**Comment by framinosona** [comment]
https://www.nuget.org/packages/Laerdal.Dfu.iOS/4.11.0.25

I'm also triggering a build on Laerdal.Dfu with that version 4.11.0, thanks for this PR

**Pull request merged**
